TARGET = Slave_Event
TARGET_SOURCES := Slave_Event.c RTE_Output_SetOutput_OSPort_Out.c RTE_SchussMotor_SetOutputValue_OSPort_Out.c RTE_StartTrigger_GetSensorValue_OSPort_In.c RTE_StopSensor_GetSensorValue_OSPort_In.c
TOPPERS_OSEK_OIL_SOURCE := Slave_Event.oil

O_PATH ?= build

include ../../../../../../../nxtOSEK/ecrobot/ecrobot.mak