TARGET = Master_Abgabe
TARGET_SOURCES := Master_Abgabe.c RTE_Output_SetOutput_OSPort_Out.c RTE_SchussMotor_SetOutputValue_OSPort_Out.c RTE_StartTrigger_GetSensorValue_OSPort_In.c RTE_StopSensor_GetSensorValue_OSPort_In.c 
TOPPERS_OSEK_OIL_SOURCE := Master_Abgabe.oil

O_PATH ?= build

include ../../../../../../../../../nxtOSEK/ecrobot/ecrobot.mak