/**
 *
 * $Id$
 */
package shootingmachineemfmodel.validation;

import org.eclipse.emf.common.util.EList;
import shootingmachineemfmodel.HWPorts;


/**
 * A sample validator interface for {@link shootingmachineemfmodel.Component}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ComponentValidator {
	boolean validate();

	boolean validateHasHWPortsComponent(EList<HWPorts> value);

	boolean validateHasRunnable(EList<shootingmachineemfmodel.Runnable> value);

}
