/**
 *
 * $Id$
 */
package shootingmachineemfmodel.validation;

import shootingmachineemfmodel.OSPortIN;


/**
 * A sample validator interface for {@link shootingmachineemfmodel.HWInput}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface HWInputValidator {
	boolean validate();

	boolean validateHas_OSPORTS_IN(OSPortIN value);

	boolean validateHasOSPORT_IN(OSPortIN value);

	boolean validateHasOSPORTIN(OSPortIN value);

}
