/**
 *
 * $Id$
 */
package shootingmachineemfmodel.validation;

import shootingmachineemfmodel.OSPortOUT;


/**
 * A sample validator interface for {@link shootingmachineemfmodel.HWOutput}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface HWOutputValidator {
	boolean validate();

	boolean validateHas_OSPORTS_OUT(OSPortOUT value);

	boolean validateHasOSPORT_OUT(OSPortOUT value);

	boolean validateHasOSPORTOUT(OSPortOUT value);

}
