/**
 *
 * $Id$
 */
package shootingmachineemfmodel.validation;

import org.eclipse.emf.common.util.EList;

import shootingmachineemfmodel.Brick;
import shootingmachineemfmodel.Component;
import shootingmachineemfmodel.Connections;
import shootingmachineemfmodel.InterBrickCommunication;

/**
 * A sample validator interface for {@link shootingmachineemfmodel.System}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SystemValidator {
	boolean validate();

	boolean validateHasComponent(EList<Component> value);
	boolean validateHasBrick(EList<Brick> value);
	boolean validateHasConnections(EList<Connections> value);

	boolean validateHasInterBrickCommunicationSystem(EList<InterBrickCommunication> value);
}
