/**
 *
 * $Id$
 */
package shootingmachineemfmodel.validation;

import org.eclipse.emf.common.util.EList;

import shootingmachineemfmodel.Alarm;
import shootingmachineemfmodel.Event;

/**
 * A sample validator interface for {@link shootingmachineemfmodel.Task}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TaskValidator {
	boolean validate();

	boolean validateHasEvent(EList<Event> value);
	boolean validateHasAlarm(EList<Alarm> value);
	boolean validateHasRunnable(EList<shootingmachineemfmodel.Runnable> value);
	boolean validateAUTOSTART(boolean value);
	boolean validatePRIORITY(int value);
	boolean validateACTIVATION(int value);
}
