TARGET = Master_AbgabeII
TARGET_SOURCES := Master_AbgabeII.c RTE_Output_SetOutput_OSPort_Out.c RTE_SchussMotor_SetOutputValue_OSPort_Out.c RTE_StartTrigger_GetSensorValue_OSPort_In.c RTE_StopSensor_GetSensorValue_OSPort_In.c 
TOPPERS_OSEK_OIL_SOURCE := Master_AbgabeII.oil

O_PATH ?= build

include ../../../../../../../../nxtOSEK/ecrobot/ecrobot.mak